### ISSUE TITLE
Can I use it to generate nonmetal clusters?

### ISSUE THREAD

**Issue by BEbillionaireUSD** [GardenGroupUO/Organisms#4]
As the title indicates, can I use it to generate nonmetal clusters? Such as B.

**Comment by cherylLbt** [comment]
Plus, can I use it to generate nonmetal clusters?

**Comment by geoffreyweal** [comment]
Hey cherylLbt

Yes you can, as long as you have a potential that can describe B. See the ASE and ASAP3 manuals to find out about how calculators work. These are the potential functions that are used in ASE

https://wiki.fysik.dtu.dk/ase/ase/calculators/calculators.html?highlight=calculator#module-ase.calculators

What potential are you using to describe B?

**Comment by GardenGroupUO** [comment]
Refer to the documentation to see how to create the RunMinimisation.py script for your Boron based cluster system 

https://organisms.readthedocs.io/en/latest/Local_Minimisation_Function.html

**Comment by GardenGroupUO** [comment]
I will assume that this question has been resolved.
