### ISSUE TITLE
Use a function that has not been defined

### ISSUE THREAD

**Issue by BEbillionaireUSD** [GardenGroupUO/Organisms#5]
In the file ```Cluster.py``` at line 205, there is ```energy = self.get_potential_energy()```. However, the class ```Cluster``` does not have a function named ```get_potential_energy()```

**Comment by geoffreyweal** [comment]
Hey cherylLbt

The Cluster object inherits the Atoms class from ASE, which contains the function get_potential_energy

See https://wiki.fysik.dtu.dk/ase/ase/atoms.html for more information about how the Atoms object and get_potential_energy works in ASE

**Comment by GardenGroupUO** [comment]
Refer to the documentation to see how to create the RunMinimisation.py script for your cluster system 

https://organisms.readthedocs.io/en/latest/Local_Minimisation_Function.html

**Comment by GardenGroupUO** [comment]
I will assume that this question has been resolved.

**Comment by BEbillionaireUSD** [comment]
Thanks! It has been resolved.

**Comment by GardenGroupUO** [comment]
Awesome! If you are using this program keep asking questions if things are not working!
